### ISSUE TITLE
Error when trying to load the extension

### ISSUE THREAD

**Issue by 0xroot-bf** [mwielgoszewski/burp-protobuf-decoder#4]
Hi,

I'm getting this error when I try to load this extension. I already have installed all the dependencies that you mentioned. The error that I'm getting is this one:

```
SyntaxError: ("mismatched input 'as' expecting COLON", ('/Users/sebas/tools/burp-protobuf-decoder/protoburp.py', 67, 39, '        except (OSError, RuntimeError) as error:\n'))

    at org.python.core.ParserFacade.fixParseError(ParserFacade.java:92)
    at org.python.core.ParserFacade.parse(ParserFacade.java:184)
    at org.python.core.Py.compile_flags(Py.java:1731)
    at org.python.core.__builtin__.execfile_flags(__builtin__.java:514)
    at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at burp.j5b.<init>(Unknown Source)
    at burp.teb.a(Unknown Source)
    at burp.sfc.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
```

Any idea? 

Thanks,

**Comment by 0xroot-bf** [comment]
Nevermind, it seemed to be an error with the jython-standalone.jar file. I downloaded it from another source and it worked, burp didn't like latest unstable version.

Closing this issue,

**Comment by mwielgoszewski** [comment]
Hi @0xroot, glad to hear you managed to resolve your issue. Note, this is expected if you're [using Jython 2.5](https://github.com/mwielgoszewski/burp-protobuf-decoder/issues/2#issuecomment-25411687). Not sure which "unstable" version you were using...
